name: Build iOS IPA

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build_ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      - name: Get dependencies
        run: flutter pub get

      # --- C'est ici que la magie op√®re ---
      - name: Update iOS Deployment Target to 15.0
        run: |
          sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = [0-9.]*/IPHONEOS_DEPLOYMENT_TARGET = 15.0/g' ios/Runner.xcodeproj/project.pbxproj
          grep -r "IPHONEOS_DEPLOYMENT_TARGET" ios/Runner.xcodeproj/project.pbxproj
      # ------------------------------------

      - name: Build iOS (No Sign)
        run: |
          flutter build ios --release --no-codesign
          mkdir -p Payload
          mv build/ios/iphoneos/Runner.app Payload
          zip -r FidelyKey.ipa Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v3
        with:
          name: FidelyKey-IPA
          path: FidelyKey.ipa